package com.company.univercity_bot.enums;

public enum AdminStatus {
    TYPING_REQUEST, TYPING_MESSAGE_UZ, TYPING_MESSAGE_RU, ENTERED_FOTO, ENTERED_BUTTON, SAVE_INFO, TYPING_MESSAGE,
    ENTERED_NAME, ENTERED_LOCATION_UZ, ENTERED_LOCATION_RU, ENTERED_CONTACT, ENTERED_IMAGE, CLICKED_DIRECTORY_INFO,
    ENTERED_DIRECTORY_INFO_UZ, ENTERED_DIRECTORY_INFO_RU, UPDATE_INFO_UZ_KUNDUZGI, UPDATE_INFO_RU, UPDATE_INFO_RU_KUNDUZGI,
    UPDATE_IMAGE_KUNDUZGI, CLICKED_DIRECTORY_INFO_KECHGI, ENTERED_DIRECTORY_INFO_UZ_KECHGI, ENTERED_DIRECTORY_INFO_RU_KECHGI,
    CLICKED_DIRECTORY_INFO_SIRTQI, ENTERED_DIRECTORY_INFO_UZ_SIRTQI, ENTERED_DIRECTORY_INFO_RU_SIRTQI, UPDATE_INFO_UZ_KECHGI,
    UPDATE_INFO_RU_KECHGI, UPDATE_IMAGE_KECHGI, UPDATE_INFO_UZ_SIRTQI, UPDATE_INFO_RU_SIRTQI, UPDATE_IMAGE_SIRTQI,
    CLICKED_DIRECTORY_INFO_MAGISTRATURA, ENTERED_DIRECTORY_INFO_UZ_MAGISTRATURA, ENTERED_DIRECTORY_INFO_RU_MAGISTRATURA,
    UPDATE_INFO_UZ_MAGISTRATURA, UPDATE_INFO_RU_MAGISTRATURA, UPDATE_IMAGE_MAGISTRATURA, UPDATE_MANZIL_UZ, UPDATE_MANZIL_RU,
    UPDATE_CONTACT, UPDATE_IMAGE, ENTERED_INFO_UZ_BIU, ENTERED_INFO_RU_BIU, ENTERED_IMAGE_BIU, UPDATE_INFO_UZ_BIU,
    UPDATE_INFO_RU_BIU, UPDATE_IMAGE_BIU, ENTERED_LITSENZIYA, ENTERED_DARAJA_UZ, ENTERED_DARAJA_RU, ENTERED_YONALISH_CRUD,
    ENTERED_BAKALAVR, ENTERED_BAKALAVR_NAME_UZ, ENTERED_MAGISTRATURA_NAME_UZ, ENTERED_BAKALAVR_YONALISH, ENTERED_BAKALAVR_NAME_RU,
    ENTERED_BAKALAVR_ID, ENTERED_MAGISTRATURA_NAME_RU, ENTERED_MAGISTRATURA_ID, ENTERED_MAGISTRATURA, ENTERED_MAGISTRATURA_YONALISH,
    DELETED_BAKALAVR_YONALISH, DELETED_BAKALAVR_NAME_UZ, DELETED_MAGISTRATURA_YONALISH, DELETED_MAGISTRATURA_NAME_UZ,
    DELETED_MAGISTRATURA_YONALISH_ICHIDA, ENTERED_SHARTNOMA_CRUD, SHARTNOMA_QOSHISH, CLICKED_CONTACT_CONNECTION,
    ENTERED_SHARTNOMA_YONALISH, ENTERED_SHARTNOMA_UZ, ENTERED_SHARTNOMA_RU, ENTERED_SHARTNOMA_OLISH, ENTERED_BAKALAVR_TARIF_UZ, ENTERED_BAKALAVR_TARIF_RU, ENTERED_MAGISTRATURA_TARIF_UZ, ENTERED_MAGISTRATURA_TARIF_RU, SHARTNOMA_UPDATE, ENTERED_SHARTNOMA_DARAJA_UPDATE, ENTERED_SHARTNOMA_YONALISH_UPDATE, ENTERED_SHARTNOMA_UZ_UPDATE, ENTERED_SHARTNOMA_RU_UPDATE, ENTERED_ROYXATDAN_OTGANLAR, ENTERED_BAKALAVR_EXCEL, ENTERED_SHARTNOMA_DARAJA
}
