package com.company.univercity_bot.enums;

public enum UserStatus {
    CHANGE_LANGUAGE_RU, TALIM_DARAJASINI_KIRITIDI, TALIM_YONALISHINI_KIRITIDI, TALIM_TURINI_KIRITIDI,
    HUDUDNI_TANLADI, JINSI_TANLADI, ISMNI_KIRITDI, TUGILGAN_KUNINI_KIRITIDI, PASSPORT_RAQAMINI_KIRITIDI,
    PASSPORT_BERILGAN_SANANI_KIRITDI, TELEFON_RAQAMINI_KIRITIDI, YASHASH_MANZILI, TALIM_OLGAN,
    DIPLOM_ATTESTAT_RASMI, RASMINI_YUBORVOTDI, OTA_ONA_TELEFON, START_BOSDI, ROYXATDAN_OTISH,
    AAAA, ORTGA_QAYTISH, TALIM_SHAKLI_SHARTNOMA_RU, TALIM_SHAKLI_SHARTNOMA_UZ,
    ABITURIENTLARGA_UZ, ABITURIENTLARGA_RU, CHANGE_LANGUAGE_UZ
}
